const zodiacSigns = [
    "Capricorn" ,"Aquarius" ,
    "Pisces", "Aries", "Taurus", "Gemini" ,
    "Cancer", "Leo","Virgo","Libra", "Scorpio", "Sagittarius"
];

const compliments = [
  "You have a magnetic personality.",
  "People feel comfortable around you.",
  "You are more capable than you realize.",
  "Your intuition is surprisingly strong.",
  "You bring calm into chaotic situations.",
  "You have a natural leadership aura.",
  "Your creativity stands out.",
  "You are emotionally intelligent.",
  "Your honesty is refreshing.",
  "You adapt well to change.",
  "You inspire people without trying.",
  "Your energy is contagious.",
  "You have a sharp mind.",
  "You see beauty where others don’t.",
  "Your patience is admirable.",
  "You have a strong sense of purpose.",
  "People trust your judgment.",
  "You are quietly confident.",
  "Your resilience is impressive.",
  "You handle pressure well.",
  "You are a good listener.",
  "Your perspective is unique.",
  "You learn from your mistakes.",
  "You balance logic and emotion well.",
  "You have a warm presence.",
  "You uplift others naturally.",
  "Your focus is powerful.",
  "You think deeply about life.",
  "You are dependable.",
  "Your growth mindset sets you apart.",
  "You are wiser than your age suggests.",
];

const victimCardComplaints = [
  "People always misunderstand me.",
  "I give more than I receive.",
  "Nothing ever goes according to plan.",
  "Others have it easier than me.",
  "I try hard, but luck never favors me.",
  "People take me for granted.",
  "No one sees my effort.",
  "I’m always the one adjusting.",
  "Things go wrong at the worst time.",
  "I get blamed even when it’s not my fault.",
  "People don’t appreciate me enough.",
  "I always end up doing extra work.",
  "Why does this always happen to me?",
  "I care more than others do.",
  "People don’t listen to me.",
  "I’m unlucky compared to others.",
  "My intentions are always doubted.",
  "I sacrifice a lot, but no one notices.",
  "I’m always stuck fixing problems.",
  "Others get credit for my work.",
  "Life feels unfair sometimes.",
  "I try to stay positive, but it’s hard.",
  "People expect too much from me.",
  "I’m always the backup option.",
  "I give chances that aren’t returned.",
  "I feel overlooked.",
  "I always have to be the mature one.",
  "My side of the story is ignored.",
  "Things would be easier if people understood me.",
  "I feel emotionally drained often.",
  "I wish things were simpler for me.",
];

const recommendations = [
  "Trust your instincts today.",
  "Take a break and recharge.",
  "Focus on one thing at a time.",
  "Avoid overthinking small issues.",
  "Speak your truth calmly.",
  "Drink more water today.",
  "Let go of what you can’t control.",
  "Spend time with someone positive.",
  "Organize your thoughts before acting.",
  "Be patient — results are coming.",
  "Don’t rush important decisions.",
  "Listen more than you speak today.",
  "Do something creative.",
  "Rest is as important as effort.",
  "Avoid unnecessary arguments.",
  "Reflect before reacting.",
  "Small progress is still progress.",
  "Trust the process.",
  "Be kind to yourself.",
  "Avoid comparing your journey.",
  "A short walk will clear your mind.",
  "Finish pending tasks first.",
  "Express gratitude today.",
  "Stay grounded in reality.",
  "Take responsibility, not pressure.",
  "Set healthy boundaries.",
  "Say no when needed.",
  "Focus on growth, not perfection.",
  "Keep emotions balanced.",
  "Believe in slow success.",
  "End the day with reflection.",
];
const form = document.getElementById('astroForm');
form.addEventListener('submit',(e)=>{
    e.preventDefault();

    const name = document.getElementById('name').value;
    const date = parseInt(document.getElementById("date")).value; 
    const month = document.getElementById("month").value;
    const year = document.getElementById('year').value;
})